Repository Mgrdich/testGoApi, pull requests merged in 2024-05, with the labels that each got.

#7 Chore/test suites
  .github/workflows/testGoApi.yml
  Makefile
  README.md
  cmd/server.go
  docker-compose.yml
  internal/controller/controller_test.go
  internal/controller/health_test.go
  internal/controller/movies.go
  internal/controller/movies_test.go
  internal/controller/person.go
  internal/controller/person_test.go
  internal/db/initializer.go
  internal/repository/interfaces.go
  internal/repository/movie_repository.go
  internal/repository/person_repository.go
  internal/routes/movies.go
  internal/routes/person.go
  internal/routes/routes.go
  internal/routes/routes_test.go
  internal/services/interfaces.go
  internal/services/memory_movie_service.go
  internal/services/memory_movie_service_test.go
  internal/services/movie_service.go
  internal/services/movie_service_test.go
  internal/services/person_service.go
  internal/services/person_service_test.go
Labels: enhancement

#8 Feat/swager
  .github/workflows/testGoApi.yml
  .gitignore
  Makefile
  README.md
  cmd/server.go
  configs/config.go
  go.mod
  go.sum
  internal/controller/health.go
  internal/controller/movies.go
  internal/controller/person.go
  internal/routes/routes.go
Labels: documentation, enhancement

#10 Fix the enviroment variables in the CI pipeline
  .github/workflows/testGoApi.yml
Labels: enhancement

#11 refactor swaggo annotations
  internal/controller/movies.go
  internal/controller/person.go
  internal/models/movies.go
  internal/models/person.go
  internal/server/errors.go
  internal/services/memory_movie_service.go
Labels: documentation

#13 add Context functionality from our controllers
  internal/controller/movies.go
  internal/controller/movies_test.go
  internal/controller/person.go
  internal/middlewares/id_context.go
  internal/repository/interfaces.go
  internal/repository/movie_repository.go
  internal/repository/person_repository.go
  internal/services/interfaces.go
  internal/services/movie_service.go
  internal/services/movie_service_test.go
  internal/services/person_service.go
  internal/util/types.go
Labels: bug, documentation

#17 Use Context to get the person in the Person Controller
  internal/controller/person.go
  internal/middlewares/id_context.go
Labels: enhancement
